# This is a basic workflow to help you get started with Actions
name: Schedule Action

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/15 * * * *' #invoke every 15 min.


jobs:
  Echo:
    runs-on: ubuntu-latest
    steps:
      - name: cmd to exec
        run: date