# This is a basic workflow to help you get started with Actions
name: Schedule Action

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/10 * * * *' #invoke every 15 min.
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Switch Environment
        required: false
        default: dev

jobs:
  Run:
    runs-on: ubuntu-latest
    environment: dev
    needs: []
    steps:      
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: pip

      - name: Install modules by requirements
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r tests/requirements.txt

      - name: put object to s3
        run: python -m .src/put_object_s3.py
      