# This is a basic workflow to help you get started with Actions
name: Schedule Action

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/60 * * * *' #invoke every 10 min.
  # workflow_dispatch:
  #   inputs:
  #     dev:
  #       type: environment
  #       required: false
  #       default: dev
  #     prod:
  #       type: environment
  #       required: false

permissions:
  id-token: write # required for cron scheduled action
  contents: read

env:
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/cron-role

jobs:
  Run:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    needs: []
    steps:      
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: pip

      - name: Debug AWS Credentials
        run: |
          echo "access_key: ${{vars.AWS_ACCESS_KEY_ID}}"
          echo "secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{vars.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-1
          # role-to-assume: ${{ env.AWS_ROLE_ARN}}

      - name: Install modules by requirements
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r tests/requirements.txt

      - name: put object to s3
        run: |
          source venv/bin/activate
          python ./src/put_object_s3.py
      